### ISSUE TITLE
Nodekit does not appear to be correctly installed via npm -g

### ISSUE THREAD

**Issue by lenkite** [nodekit-io/nodekit#12]
Installed nodekit via `npm -g`. Installation was successful. Attempted to create a project
via `nodekit create myApp io.nodekit.myApp myApp`. Got the error:
`Creating a new nodekit project.
cp: no such file or directory: /usr/local/lib/node_modules/nodekit/node_modules/nodekit-sample/www/*`

**Comment by guybarnard** [comment]
Thanks, in process of updating to latest nodekit command line client.  For now the new command line client is installed with `npm install -g nodekit-cli` instead of `npm install -g nodekit`.   Eventually will remap to nodekit.    To try in interim probably best to `npm uninstall -g nodekit` first.    

Will update instructions here.  Thanks.

**Comment by lenkite** [comment]
Hi, Sorry for the delay. Installed nodekit via nodekit-cli. Now, attempting to create an application throws an error. Using latest version of npm (4.2.0) and node js (7.9.0) at this time.
```
nodekit -d create myapp io.nodekit.myapp myapp

Using detached nodekit-create
Creating a new nodekit project.
Copying assets."
index.js does not specify valid sub-directory: /usr/local/lib/node_modules/nodekit-cli/src/node_modules/nodekit-sample
Error: Error
    at /usr/local/lib/node_modules/nodekit-cli/src/nodekit-cli-lib/nodekit-cli-create/index.js:237:19
    at _fulfilled (/usr/local/lib/node_modules/nodekit-cli/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/nodekit-cli/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/nodekit-cli/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/nodekit-cli/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/nodekit-cli/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/nodekit-cli/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
```

**Comment by perqa** [comment]
Same problem here, but with slightly different error message. Using nodekit-cli does not seem to help.

```
npm install -g nodekit-cli
nodekit create myapp io.nodekit.myapp myapp

Error: Could not find directory: /Users/<USER>/.nvm/versions/node/v7.6.0/lib/node_modules/nodekit-cli/src/node_modules/nodekit-sample

node --version
v7.6.0

npm --version
4.1.2

nvm --version
0.30.2

pod --version
1.2.0

pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 8.2.0.0.1.1480973914
volume: /
location: /
install-time: 1482851976
groups: com.apple.FindSystemFiles.pkg-group 

sw_vers -productVersion 
10.11.6

**Comment by d4hines** [comment]
I got the same error as @perqa on Node v8.11.3, npm v5.6.0 and pod v1.5.3. I have no prior experience with nodekit, and just looking to try it out. Does anyone have any way around this?
