### ISSUE TITLE
Very interesting! Is this still 'on'?

### ISSUE THREAD

**Issue by ChristianWeyer** [nodekit-io/nodekit#7]
Hi there,

this project really looks promising. Are you still actively working on it?
Thanks!

**Comment by voxsoftware** [comment]
I want to know the same too. Is active the project?

**Comment by guycreate** [comment]
Sorry for tardiness the short answer is yes, still active;  the longer answer is its intertwined with a commercial application I am leading a company for, and so some of the active development in last couple of months was more on example apps than on the core framework.  This should change over next couple of weeks as the core framework will be useful to the commercial project I think.  

So for near term application say next 3 months, I'd say contributors welcome and go at your own risk with emerging product.  For longer term application say 3-12 months, I'd say expect some significant development on iOS and Android with robustness for millions of users for at least core parts, with some care and feeding to Windows.  The example app will now probably be more react/preact/firebase/horizon based as the current jquery just doesnt have as much commercial fit I think.

**Comment by DylanPiercey** [comment]
@guycreate this project would be amazing.

**Comment by guycreate** [comment]
Thanks!   The API for darwin based operating systems (OSX/MacOS/iOS to start) has settled in last couple of weeks, and so development can progress on Android.    More to come soon.

**Comment by jkutemeier** [comment]
I've been attempting to build/run on Sierra beta and iOS 10, and as I expect, ran into some issues.  I'm wondering, is there anything that I can contribute along those lines, or am I better off waiting for the next checkin/merge?

**Comment by max-pub** [comment]
I think it would make a lot of sense to publish sth soon as a lot of people are searching for a lightweight replacement for their chromeOS-apps... 
NodeKit would be better positioned than Electron/NW with their huge package-sizes.

**Comment by guycreate** [comment]
@max-pub Thanks for feedback, yes great point on Chrome-apps.    Ups the urgency.

@jkutemeier it may make sense to start contributing on the darwin side as progress in next couple of weeks will be getting first cut of Android to site, but will circle back after that to align all three major platform families including testing on Sierra and iOS 10. 

The darwin side is currently developed against iOS 10 but so far only El Capitan as previous Sierra betas didn't run well on memory limited 4Gb MacBooks.

**Comment by jkutemeier** [comment]
@guycreate My machine has 24GB and the latest Sierra Beta and XCode beta installed. Has any of the code changed in that repo since the last merge to master? If not, I'd be willing to take a stab at getting it converted over to Swift 3.0.

**Comment by guycreate** [comment]
No, both nodekit-darwin and nodekit-darwin-lite are current on master.  Conversion to Swift 3.0 appreciated.

**Comment by centaur1** [comment]
When I do a clean install on OS X 10.12 with only iOS installed, I get:

1.** BUILD SUCCEEDED **

TypeError: Cannot read property 'split' of undefined
    at SimctlListParser.parse (/Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/simctl/lib/simctl-list-parser.js:46:9)
    at Object.list (/Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/simctl/simctl.js:172:35)
    at Object.getdevicetypes (/Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/ios-sim/src/lib.js:255:27)
    at Object.listEmulatorImages [as run] (/Users/me/Developer/myapp/platforms/ios/nodekit/lib/list-emulator-images:34:29)
    at deployToSim (/Users/me/Developer/myapp/platforms/ios/nodekit/lib/run.js:142:50)
    at /Users/me/Developer/myapp/platforms/ios/nodekit/lib/run.js:84:20
    at _fulfilled (/Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/q/q.js:796:13)
    at /Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/q/q.js:604:44
**Error: Cannot read property 'runtimes' of undefined**

Any suggestions?


2.  Also on the README.md file, I believe that:
"nodekit platform add macos"
should be
"nodekit platform add osx" 
right now given that nodekit platform list shows:
Available platforms: 
  amazon-fireos ~1.0.0 (deprecated)
  android ~1.0.0
  browser ~1.0.0
  ios 4.2.1
  osx ~1.0.0

**Comment by PierBover** [comment]
I'm writing a universal app that has to run on iOS and Android using Cordova, Windows and Mac using Electron, and also Chrome OS. My UI is the same code base for all targets, but the backend is different. For example in Electron I use Node for interacting with the file system, but not in Cordova or Chrome OS.

It's a bit late to use Nodekit for this one, but I would **love** to use it for future cross platform projects.

What's the status of the project?

The last code commit is from 2 years ago which is quote worrying. But this is such a great idea. Removing bloat and having cross platform backend code is genius.
