### ISSUE TITLE
Error: Cannot read property 'runtimes' of undefined

### ISSUE THREAD

**Issue by centaur1** [nodekit-io/nodekit#9]
When I do a clean install on OS X 10.12 with only iOS installed, I get:

1.** BUILD SUCCEEDED **

TypeError: Cannot read property 'split' of undefined
at SimctlListParser.parse (/Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/simctl/lib/simctl-list-parser.js:46:9)
at Object.list (/Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/simctl/simctl.js:172:35)
at Object.getdevicetypes (/Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/ios-sim/src/lib.js:255:27)
at Object.listEmulatorImages as run
at deployToSim (/Users/me/Developer/myapp/platforms/ios/nodekit/lib/run.js:142:50)
at /Users/me/Developer/myapp/platforms/ios/nodekit/lib/run.js:84:20
at _fulfilled (/Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/q/q.js:834:54)
at self.promiseDispatch.done (/Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/q/q.js:863:30)
at Promise.promise.promiseDispatch (/Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/q/q.js:796:13)
at /Users/me/Developer/myapp/platforms/ios/nodekit/node_modules/q/q.js:604:44
Error: Cannot read property 'runtimes' of undefined

Any suggestions?

2. Also on the README.md file, I believe that: "nodekit platform add macos" should be "nodekit platform add osx" right now given that nodekit platform list shows: Available platforms: amazon-fireos ~1.0.0 (deprecated) android ~1.0.0 browser ~1.0.0 ios 4.2.1 osx ~1.0.0

**Comment by guycreate** [comment]
On the README, Yes I started to use macos for all the nodekit-cli commands but then realized this might be a waste of time as we are mostly just leveraging the hard work of many years of others for the generator code which of course assumed osx.  Curious if there are strong feelings either way, otherwise will need to update the readme to revert back to OSX.  I noticed that a lot of new Xcode code seems to use macOSX which seems to be a nice hybrid.    It's easy of course to change the CLI itself but if we do it, I wanted to make sure the directory structure (platforms/) etc all reflected the same change.

The ios and osx generators are not yet ready, as even if you solve the above it is not yet using the actual nodekit xcodeproj template, and so I wouldnt expect any app to launch.  This is only a few days away though, as I felt that getting the CLI going was well worth it before publicizing this project, but only got to clean BUILD yesterday for the ios command line generator!

**Comment by centaur1** [comment]
I don't think it matters whether it is osx or macos.  Given Apple is transitioning to macos, perhaps that is the best choice - but I have no strong feelings.

As far as the iOS and osx generators, great news, can't wait to try them!

Thanks
